version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_fullName: lexis_postgres
    restart: always
    environment:
      POSTGRES_USER: lexis_user
      POSTGRES_PASSWORD: lexis_password
      POSTGRES_DB: lexis_db
    ports:
      - "5432:5432"
    volumes:
      - lexis_postgres_data:/var/lib/postgresql/data

volumes:
  lexis_postgres_data:
