import { useState } from 'react';
import { ai } from '../services/api';
import { FileCheck, Download, Copy, Loader2, Shield, Info, Gavel } from 'lucide-react';
import { jsPDF } from 'jspdf';

const DocumentGenerator = () => {
  const [selectedTemplate, setSelectedTemplate] = useState('');
  const [details, setDetails] = useState('');
  const [result, setResult] = useState('');
  const [loading, setLoading] = useState(false);

  const templates = [
    { id: 'affidavit', name: 'Affidavit', fields: 'Deponent Name, Father/Husband Name, Address, Statement of Facts' },
    { id: 'notice', name: 'Legal Notice', fields: 'Sender Name, Recipient Name, Matter of Dispute, Demands' },
    { id: 'power', name: 'Power of Attorney', fields: 'Principal Name, Attorney Name, Specific Powers, Property Details' },
    { id: 'agreement', name: 'Agreement Draft', fields: 'First Party, Second Party, Subject Matter, Terms and Conditions' },
    { id: 'application', name: 'Court Application', fields: 'Court Name, Case Title, Specific Relief or Prayer' },
  ];

  const handleGenerate = async () => {
    if (!selectedTemplate || !details.trim()) return;
    setLoading(true);
    try {
      const fullPrompt = `Generate a professional ${selectedTemplate} according to Pakistani law standards. 
      Details provided: ${details}. 
      Format the output as a formal legal document suitable for submission in a Pakistani court or official use.`;
      
      const res = await ai.generateDraft(fullPrompt);
      setResult(res.data.draft);
    } catch (err) {
      console.error('Generation Error:', err);
      setResult('Error generating document. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(result);
    alert('Copied to clipboard!');
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    
    // Add header
    doc.setFontSize(20);
    doc.setTextColor(10, 31, 65); // legal-blue
    doc.text('NISAR HUSSAIN VIRTUAL LAW CHAMBER', 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text('PROFESSIONAL LEGAL DOCUMENT GENERATOR', 105, 28, { align: 'center' });
    
    // Add line
    doc.setDrawColor(190, 160, 110); // legal-gold
    doc.setLineWidth(0.5);
    doc.line(20, 32, 190, 32);
    
    // Add title
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text(`${selectedTemplate} Draft`, 20, 42);
    
    // Add content
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const splitText = doc.splitTextToSize(result, 170);
    doc.text(splitText, 20, 52);
    
    // Add footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
      doc.text('Generated by Lexis AI Suite - Advocate Nisar Hussain Bhatti', 105, 290, { align: 'center' });
    }
    
    doc.save(`${selectedTemplate.replace(/\s+/g, '_')}_${new Date().getTime()}.pdf`);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-8 py-8 animate-in fade-in duration-500">
      <div className="flex items-center space-x-4 border-b border-slate-200 pb-6">
        <div className="bg-legal-blue p-3 rounded-sm shadow-lg">
          <FileCheck className="w-8 h-8 text-legal-gold" />
        </div>
        <div>
          <h1 className="text-3xl font-serif font-bold text-legal-blue">Legal Document Generator</h1>
          <p className="text-xs text-slate-500 uppercase tracking-widest font-bold">Automated Drafting Suite – Advocate Nisar Hussain Bhatti</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="space-y-6">
          <div className="bg-white p-6 rounded-sm shadow-md border border-slate-100">
            <h3 className="text-sm font-bold text-legal-blue uppercase tracking-widest mb-4">Select Template</h3>
            <div className="space-y-2">
              {templates.map((t) => (
                <button
                  key={t.id}
                  onClick={() => setSelectedTemplate(t.name)}
                  className={`w-full text-left px-4 py-3 rounded-sm text-xs font-bold transition-all border ${
                    selectedTemplate === t.name 
                      ? 'bg-legal-blue text-white border-legal-blue' 
                      : 'bg-slate-50 text-slate-500 border-slate-200 hover:border-legal-gold'
                  }`}
                >
                  {t.name}
                </button>
              ))}
            </div>
          </div>

          <div className="bg-legal-gold/10 p-6 rounded-sm border border-legal-gold/20">
            <div className="flex items-center gap-2 text-legal-blue mb-2">
              <Info className="w-4 h-4" />
              <h4 className="text-xs font-bold uppercase">Instructions</h4>
            </div>
            <p className="text-[10px] text-slate-600 leading-relaxed">
              Select a template and enter the required details like names, addresses, and facts. 
              The AI will generate a legally compliant draft in standard Pakistani format.
            </p>
          </div>
        </div>

        <div className="lg:col-span-2 space-y-6">
          <div className="bg-white p-8 rounded-sm shadow-xl border border-slate-100">
            <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-4">
              {selectedTemplate ? `Details for ${selectedTemplate}` : 'Select a template to begin'}
            </label>
            <textarea
              className="w-full p-6 bg-white text-black border border-slate-200 rounded-sm focus:ring-2 focus:ring-legal-gold focus:border-transparent focus:outline-none min-h-[200px] text-sm leading-relaxed placeholder:text-slate-300"
              placeholder={selectedTemplate 
                ? `Enter: ${templates.find(t => t.name === selectedTemplate)?.fields}` 
                : "Please select a template from the left sidebar first..."
              }
              disabled={!selectedTemplate}
              value={details}
              onChange={(e) => setDetails(e.target.value)}
            />
            
            <button
              onClick={handleGenerate}
              disabled={loading || !selectedTemplate || !details.trim()}
              className="w-full mt-6 bg-legal-blue text-white py-4 rounded-sm font-bold flex items-center justify-center space-x-3 hover:bg-black transition-all disabled:opacity-50 shadow-lg uppercase tracking-widest text-xs"
            >
              {loading ? <Loader2 className="w-5 h-5 animate-spin text-legal-gold" /> : <Gavel className="w-5 h-5 text-legal-gold" />}
              <span>{loading ? 'Generating Document...' : 'Generate Professional Draft'}</span>
            </button>
          </div>

          {result && (
            <div className="bg-white p-8 rounded-sm shadow-2xl border-t-4 border-legal-gold animate-in slide-in-from-bottom duration-500">
              <div className="flex justify-between items-center mb-6 pb-4 border-b border-slate-100">
                <div className="flex items-center space-x-2">
                  <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                  <h3 className="text-lg font-serif font-bold text-legal-blue">Generated Draft</h3>
                </div>
                <div className="flex space-x-2">
                  <button 
                    onClick={copyToClipboard}
                    className="p-2.5 bg-slate-50 hover:bg-legal-gold hover:text-black rounded-sm transition-all text-slate-600 border border-slate-100"
                    title="Copy to Clipboard"
                  >
                    <Copy className="w-5 h-5" />
                  </button>
                  <button 
                    onClick={downloadPDF}
                    className="p-2.5 bg-slate-50 hover:bg-legal-blue hover:text-white rounded-sm transition-all text-slate-600 border border-slate-100"
                    title="Download as PDF"
                  >
                    <Download className="w-5 h-5" />
                  </button>
                </div>
              </div>
              <div className="bg-slate-50 p-8 rounded-sm border border-slate-200">
                <div className="prose prose-slate max-w-none whitespace-pre-wrap text-slate-800 font-serif text-sm leading-loose">
                  {result}
                </div>
              </div>
              <div className="mt-6 flex items-center justify-center gap-2 text-slate-400">
                <Shield className="w-4 h-4 text-legal-gold" />
                <span className="text-[10px] font-bold uppercase tracking-widest">Verified Legal Format</span>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default DocumentGenerator;
