import { useState } from 'react';
import { ai } from '../services/api';
import { Sparkles, FileText, Search, Copy, Download, Loader2, Shield, Gavel, Book, FileCheck, Info } from 'lucide-react';
import { jsPDF } from 'jspdf';

const LegalAssistant = () => {
  const [prompt, setPrompt] = useState('');
  const [result, setResult] = useState('');
  const [loading, setLoading] = useState(false);
  const [type, setType] = useState<'DRAFT' | 'RESEARCH' | 'GENERATE' | 'SEARCH'>('DRAFT');
  const [selectedTemplate, setSelectedTemplate] = useState('');

  const templates = [
    { id: 'affidavit', fullName: 'Affidavit', fields: ['Deponent Name', 'Father/Husband Name', 'Address', 'Purpose'] },
    { id: 'notice', fullName: 'Legal Notice', fields: ['Sender Name', 'Recipient Name', 'Matter', 'Demands'] },
    { id: 'power', fullName: 'Power of Attorney', fields: ['Principal Name', 'Attorney Name', 'Powers Granted'] },
    { id: 'agreement', fullName: 'Agreement Draft', fields: ['Party A', 'Party B', 'Subject', 'Terms'] },
    { id: 'application', fullName: 'Court Application', fields: ['Court Name', 'Case Title', 'Relief Sought'] },
  ];

  const handleGenerate = async () => {
    if (!prompt.trim() && !selectedTemplate) return;
    setLoading(true);
    try {
      let fullPrompt = '';
      if (type === 'DRAFT') {
        fullPrompt = `Draft a professional legal document for: ${prompt}. Use Pakistani legal terminology and formal format according to the standards of High Courts in Pakistan.`;
      } else if (type === 'RESEARCH') {
        fullPrompt = `Conduct in-depth legal research on the following topic under Pakistani Law: ${prompt}. Provide relevant sections from the Pakistan Penal Code (PPC), Code of Criminal Procedure (CrPC), Civil Procedure Code (CPC), and the Constitution of Pakistan. Cite relevant case law precedents if possible.`;
      } else if (type === 'GENERATE') {
        fullPrompt = `Generate a professional ${selectedTemplate} according to Pakistani law standards with the following details: ${prompt}. Ensure the language is formal and legally binding in Pakistan.`;
      } else if (type === 'SEARCH') {
        fullPrompt = `Explain Section ${prompt} of Pakistani Law. Search across PPC, CrPC, CPC, and the Constitution. Provide the exact text of the section, a detailed professional explanation, and cross-references to other related legal acts.`;
      }
      
      const res = await ai.generateDraft(fullPrompt);
      setResult(res.data.draft);
    } catch (err) {
      console.error('AI Error:', err);
      setResult('Failed to connect to AI service. Please verify your connection or contact support.');
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(result);
    alert('Copied to clipboard!');
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    
    // Add header
    doc.setFontSize(20);
    doc.setTextColor(10, 31, 65); // legal-blue
    doc.text('NISAR HUSSAIN VIRTUAL LAW CHAMBER', 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text('AI-GENERATED LEGAL DOCUMENT', 105, 28, { align: 'center' });
    
    // Add line
    doc.setDrawColor(190, 160, 110); // legal-gold
    doc.setLineWidth(0.5);
    doc.line(20, 32, 190, 32);
    
    // Add title based on type
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    const title = type === 'SEARCH' ? 'Legal Explanation' : (type === 'GENERATE' ? `${selectedTemplate} Draft` : 'Legal Draft');
    doc.text(title, 20, 42);
    
    // Add content
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const splitText = doc.splitTextToSize(result, 170);
    doc.text(splitText, 20, 52);
    
    // Add footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
      doc.text('Generated by Lexis AI Suite - Advocate Nisar Hussain Bhatti', 105, 290, { align: 'center' });
    }
    
    doc.save(`${title.replace(/\s+/g, '_')}_${new Date().getTime()}.pdf`);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-8 py-4 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 border-b border-slate-200 pb-6">
        <div className="flex items-center space-x-4">
          <div className="bg-legal-blue p-3 rounded-sm shadow-lg">
            <Sparkles className="w-8 h-8 text-legal-gold" />
          </div>
          <div>
            <h1 className="text-3xl font-serif font-bold text-legal-blue">Lexis AI Legal Suite</h1>
            <p className="text-xs text-slate-500 uppercase tracking-widest font-bold">Advocate Nisar Hussain Bhatti – Intelligence Terminal</p>
          </div>
        </div>
        <div className="flex items-center space-x-2 text-slate-400 bg-slate-50 px-4 py-2 rounded-full text-xs font-bold border border-slate-100">
          <Shield className="w-4 h-4 text-legal-gold" />
          <span>Secure Encrypted Session</span>
        </div>
      </div>
      
      <div className="bg-white p-8 rounded-sm shadow-xl border border-slate-100 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-32 h-32 bg-legal-gold/5 rounded-full -mr-16 -mt-16"></div>
        
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8 relative z-10">
          <button 
            onClick={() => setType('DRAFT')}
            className={`flex flex-col items-center justify-center p-4 rounded-sm border-2 transition-all uppercase tracking-widest text-[9px] font-bold gap-2 ${
              type === 'DRAFT' ? 'border-legal-blue bg-legal-blue text-white shadow-lg' : 'border-slate-100 bg-slate-50 text-slate-500 hover:border-legal-gold'
            }`}
          >
            <FileText className="w-5 h-5" />
            <span>Drafting</span>
          </button>
          <button 
            onClick={() => setType('RESEARCH')}
            className={`flex flex-col items-center justify-center p-4 rounded-sm border-2 transition-all uppercase tracking-widest text-[9px] font-bold gap-2 ${
              type === 'RESEARCH' ? 'border-legal-blue bg-legal-blue text-white shadow-lg' : 'border-slate-100 bg-slate-50 text-slate-500 hover:border-legal-gold'
            }`}
          >
            <Search className="w-5 h-5" />
            <span>Research</span>
          </button>
          <button 
            onClick={() => setType('GENERATE')}
            className={`flex flex-col items-center justify-center p-4 rounded-sm border-2 transition-all uppercase tracking-widest text-[9px] font-bold gap-2 ${
              type === 'GENERATE' ? 'border-legal-blue bg-legal-blue text-white shadow-lg' : 'border-slate-100 bg-slate-50 text-slate-500 hover:border-legal-gold'
            }`}
          >
            <FileCheck className="w-5 h-5" />
            <span>Generator</span>
          </button>
          <button 
            onClick={() => setType('SEARCH')}
            className={`flex flex-col items-center justify-center p-4 rounded-sm border-2 transition-all uppercase tracking-widest text-[9px] font-bold gap-2 ${
              type === 'SEARCH' ? 'border-legal-blue bg-legal-blue text-white shadow-lg' : 'border-slate-100 bg-slate-50 text-slate-500 hover:border-legal-gold'
            }`}
          >
            <Book className="w-5 h-5" />
            <span>Law Search</span>
          </button>
        </div>

        <div className="space-y-6 relative z-10">
          {type === 'GENERATE' && (
            <div className="grid grid-cols-1 md:grid-cols-5 gap-2 mb-4">
              {templates.map(t => (
                <button 
                  key={t.id}
                  onClick={() => setSelectedTemplate(t.name)}
                  className={`py-2 px-1 text-[8px] font-bold uppercase tracking-widest rounded-sm border ${
                    selectedTemplate === t.name ? 'bg-legal-gold text-black border-legal-gold' : 'bg-slate-50 text-slate-400 border-slate-200 hover:border-legal-gold'
                  }`}
                >
                  {t.name}
                </button>
              ))}
            </div>
          )}

          <div className="relative">
            <textarea 
              className="w-full p-6 bg-white text-black border border-slate-200 rounded-sm focus:ring-2 focus:ring-legal-gold focus:border-transparent focus:outline-none min-h-[180px] text-sm leading-relaxed placeholder:text-slate-400"
              placeholder={
                type === 'DRAFT' ? "Describe the document you need..." : 
                type === 'RESEARCH' ? "Enter the legal topic or question..." :
                type === 'GENERATE' ? `Enter details for ${selectedTemplate || 'document'} (Names, Dates, Facts)...` :
                "Enter Section Number & Act (e.g., Section 302 PPC, Section 491 CrPC)..."
              }
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
            />
            <div className="absolute bottom-4 right-4 text-[10px] font-bold text-slate-400 uppercase tracking-widest flex items-center gap-2">
              <Info className="w-3 h-3" /> Pakistani Law Expert Mode
            </div>
          </div>
          
          <button 
            onClick={handleGenerate}
            disabled={loading || (!prompt.trim() && !selectedTemplate)}
            className="w-full bg-legal-blue text-white py-5 rounded-sm font-bold flex items-center justify-center space-x-3 hover:bg-black transition-all disabled:opacity-50 shadow-xl uppercase tracking-widest text-xs"
          >
            {loading ? <Loader2 className="w-5 h-5 animate-spin text-legal-gold" /> : <Gavel className="w-5 h-5 text-legal-gold" />}
            <span>{loading ? 'Processing Legal Intelligence...' : `Begin AI ${type}`}</span>
          </button>
        </div>
      </div>

      {result && (
        <div className="bg-white p-8 rounded-sm shadow-2xl border-t-4 border-legal-gold animate-in slide-in-from-bottom duration-500">
          <div className="flex justify-between items-center mb-6 pb-4 border-b border-slate-100">
            <div className="flex items-center space-x-2">
              <div className="w-2 h-2 bg-green-500 rounded-full"></div>
              <h3 className="text-lg font-serif font-bold text-legal-blue">
                {type === 'SEARCH' ? 'Legal Explanation & Reference' : 'AI Generated Professional Draft'}
              </h3>
            </div>
            <div className="flex space-x-2">
              <button 
                onClick={copyToClipboard} 
                className="p-2.5 bg-slate-50 hover:bg-legal-gold hover:text-black rounded-sm transition-all text-slate-600 shadow-sm border border-slate-100" 
                title="Copy to Clipboard"
              >
                <Copy className="w-5 h-5" />
              </button>
              <button 
                onClick={downloadPDF}
                className="p-2.5 bg-slate-50 hover:bg-legal-blue hover:text-white rounded-sm transition-all text-slate-600 shadow-sm border border-slate-100" 
                title="Download as PDF"
              >
                <Download className="w-5 h-5" />
              </button>
            </div>
          </div>
          <div className="bg-slate-50 p-8 rounded-sm border border-slate-200">
            <div className="prose prose-slate max-w-none whitespace-pre-wrap text-slate-800 font-serif text-sm leading-loose">
              {result}
            </div>
          </div>
          <p className="mt-6 text-[10px] text-slate-400 italic text-center uppercase tracking-widest">
            Always review AI outputs for accuracy before formal legal filing.
          </p>
        </div>
      )}
    </div>
  );
};

export default LegalAssistant;
